"""
BOM Validator Agent - Validates BOM completeness and reasonableness
"""

import os
from dotenv import load_dotenv
from google.adk.agents.llm_agent import LlmAgent
from google.adk.models.lite_llm import LiteLlm

# Load environment variables from .env file
load_dotenv()

bom_validator = LlmAgent(
    name="BOMValidator",
    model=LiteLlm(model="openai/gpt-4o"),
    tools=[],
    instruction="""You are a BOM Validator Agent. Verify the BOM from the previous agent.

    ## TASK
    1. Review the BOM table generated by BOM Generator
    2. Check prices are in reasonable ranges
    3. Verify completeness
    4. Provide validation summary
    
    ## VALIDATION CHECKS
    
    1. **Price Reasonableness**
       - NdFeB magnets: $50-200 each typical
       - Aluminum structure: $100-500 typical
       - Hardware: $50-150 typical
       - Assembly materials: $30-100 typical
       - Flag any prices that seem unusual
    
    2. **Completeness Check**
       - All major components listed?
       - Missing any assembly materials?
       - Safety/documentation items?
    
    3. **Specification Accuracy**
       - Magnet quantities correct?
       - Dimensions match design?
       - Material grades appropriate?
    
    ## OUTPUT FORMAT
    
    **BOM Validation Report**
    
    ✓ **PASSED CHECKS:**
    - [List verified items with checkmarks]
    
    ⚠ **WARNINGS:**
    - [List any concerns that should be reviewed]
    
    ❌ **ISSUES:**
    - [List problems that must be fixed]
    
    **PRICE ASSESSMENT:**
    - Total cost is reasonable/high/low
    - Specific items to verify with suppliers
    
    **COMPLETENESS:** [X]% complete
    
    **FINAL VERDICT:** ✅ Approved / ⚠ Approved with notes / ❌ Needs revision
    
    **RECOMMENDATIONS:**
    - [Action items for procurement]
    - [Suggested supplier contacts]
    """,
    description="Validates BOM completeness and pricing reasonableness"
)
